// @app/svelte-client/src/main/infraestructure/MainWraper.svelte
<script lang="ts">
    import { mainWrapperLogic } from "@mono/core"
    import { stateFactoryProvider } from "../../core/infraestructure/state-factory/useStoreStatefactory"
    import MainPage from "./MainPage.svelte"

    const { openSate, onOpenClose } = mainWrapperLogic(stateFactoryProvider())
    let openValue = openSate.value
    openSate.subscribe((value) => {
        openValue = value
    })
</script>

<button on:click={onOpenClose}>
    {openValue ? 'Close': 'Open'}
</button>

{#if openValue}
    <div >
        <MainPage />
    </div>
{/if}

// @app/vue-client/src/main/page/MainWraper.vue
<script setup lang="ts">
import { mainWrapperLogic } from "@mono/core"
import { stateFactoryProvider } from "../../core/state-factory/state-factory"
import MainPage from "./MainPage.vue";

const { openSate, onOpenClose } = mainWrapperLogic(stateFactoryProvider())

</script>

<template>
  <button @click="onOpenClose">{{ openSate.value ? 'Close' : 'Open' }}</button>
  <div v-if="openSate.value">
    <MainPage />
  </div>
</template>
