// @app/solid-client/src/main/infraestructure/page/MainWraper.tsx
import { mainWrapperLogic } from '@mono/core'
import { signalStateFactory } from '../../../core/infraestructure/state-factory/signalStateFactory'
import Main from './MainPage'

export default function MainWraper() {
    const { openSate, onOpenClose } = mainWrapperLogic(signalStateFactory())

    return (
        <div>
            <button onClick={onOpenClose}>
                {openSate.value ? 'Close' : 'Open'}
            </button>
            {openSate.value && <Main />}
        </div>
    )
}

// @app/vue-client/src/main/page/MainWraper.vue
<script setup lang="ts">
import { mainWrapperLogic } from "@mono/core"
import { stateFactoryProvider } from "../../core/state-factory/state-factory"
import MainPage from "./MainPage.vue";

const { openSate, onOpenClose } = mainWrapperLogic(stateFactoryProvider())

</script>

<template>
  <button @click="onOpenClose">{{ openSate.value ? 'Close' : 'Open' }}</button>
  <div v-if="openSate.value">
    <MainPage />
  </div>
</template>
